import React from 'react';
import { BellRing, AlertTriangle, Shield, CheckCircle2, Download, ArrowUpRight } from 'lucide-react';
import { MOCK_ALERTS } from '../../data/mockData';
import { IntelDrawerData } from '../../types';

interface ReportsAlertsProps {
  onSelectIntel: (intel: IntelDrawerData) => void;
  onOpenReportModal: () => void;
}

export const ReportsAlertsPage: React.FC<ReportsAlertsProps> = ({ onSelectIntel, onOpenReportModal }) => {
  return (
    <div className="space-y-6">
      <div className="p-4 rounded-2xl bg-[#0F1420] border border-slate-800 flex items-center justify-between shadow-xl">
        <div>
          <h2 className="text-base font-bold font-display text-white flex items-center gap-2">
            <BellRing className="w-5 h-5 text-amber-400" />
            Intelligence Reports & Live Alert Dispatch Console
          </h2>
          <p className="text-xs text-slate-400 font-mono mt-0.5">
            Real-time automated anomaly alerts generated by SCRB predictive models
          </p>
        </div>

        <button
          onClick={onOpenReportModal}
          className="px-4 py-2 rounded-lg bg-blue-600 hover:bg-blue-500 text-white text-xs font-semibold flex items-center gap-2 shadow-md"
        >
          <Download className="w-4 h-4" /> Export Intelligence Dossier
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {MOCK_ALERTS.map((alert) => (
          <div
            key={alert.id}
            onClick={() =>
              onSelectIntel({
                type: 'anomaly',
                title: alert.title,
                subtitle: `${alert.district} • ${alert.policeStation}`,
                data: alert,
              })
            }
            className="p-5 rounded-2xl bg-[#0F1420] border border-slate-800 hover:border-amber-500/60 transition-all cursor-pointer space-y-3 shadow-lg"
          >
            <div className="flex items-center justify-between gap-2">
              <span
                className={`px-2.5 py-1 text-[10px] font-mono font-bold rounded ${
                  alert.severity === 'CRITICAL'
                    ? 'bg-red-500/20 text-red-400 border border-red-500/40'
                    : 'bg-amber-500/20 text-amber-400 border border-amber-500/40'
                }`}
              >
                {alert.severity} PRIORITY
              </span>

              <span className="text-xs text-slate-400 font-mono">{alert.timestamp}</span>
            </div>

            <div>
              <h3 className="font-bold font-display text-sm text-white">{alert.title}</h3>
              <div className="text-xs text-slate-400 font-mono mt-0.5">
                {alert.district} • {alert.policeStation}
              </div>
            </div>

            <p className="text-xs text-slate-300 leading-relaxed bg-[#161E2E] p-3 rounded-xl border border-slate-800">
              {alert.description}
            </p>

            <div className="flex items-center justify-between text-xs font-mono text-emerald-400 pt-2 border-t border-slate-800">
              <span>AI Model Confidence: {alert.aiConfidence}%</span>
              <span className="flex items-center gap-1 font-bold text-blue-400">
                Inspect Briefing <ArrowUpRight className="w-3.5 h-3.5" />
              </span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
